// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmEiVpraYJvn8chtrCOq4Am5UKJai4FP0',
    appId: '1:844894233705:web:ea0dbe9424a4bc93a1eef8',
    messagingSenderId: '844894233705',
    projectId: 'food2go-44539',
    authDomain: 'food2go-44539.firebaseapp.com',
    storageBucket: 'food2go-44539.appspot.com',
    measurementId: 'G-47T7N2B5HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG2St4s8g1UZC3p9r16S5kzDoLjkB7X5k',
    appId: '1:844894233705:android:3bdeb8cf759a7076a1eef8',
    messagingSenderId: '844894233705',
    projectId: 'food2go-44539',
    storageBucket: 'food2go-44539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0sdFbasNEu4UIx683vow1EXRvhqbMHh8',
    appId: '1:844894233705:ios:18db2cbc0bc04835a1eef8',
    messagingSenderId: '844894233705',
    projectId: 'food2go-44539',
    storageBucket: 'food2go-44539.appspot.com',
    iosBundleId: 'com.example.cptonFood2goRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0sdFbasNEu4UIx683vow1EXRvhqbMHh8',
    appId: '1:844894233705:ios:1085e2c7b2310e28a1eef8',
    messagingSenderId: '844894233705',
    projectId: 'food2go-44539',
    storageBucket: 'food2go-44539.appspot.com',
    iosBundleId: 'com.example.cptonFood2goRider.RunnerTests',
  );
}
